### ISSUE TITLE
Layout, Styling Enhancements

### ISSUE THREAD

**Issue by tankbottoms** [DAOLABS-WTF/daolabs-legal-documents#12]
1. Add next and previous at the bottom of the page, ala https://infima.dev/docs/components/pagination-nav
2. Add fixed-width breakpoint, stacking for body so that outline doesn't overlap with the body text, see http://localhost:5173/legal/ccorp/4-Bylaws.md and image below.

![Screen Shot 2022-09-13 at 12 19 40 AM](https://user-images.githubusercontent.com/97219477/189807986-f3ddf660-1e28-4376-b172-e3189372496d.png)

3. Update, refresh outline when documents are updated 
4. Checkboxes 
5. Collapsable navigation 
6. TBD - layout - discuss with tankbottoms
7. Markdown or HTML for page breaks, i.e. Exhibit, Signature page to follow, etc. 
8. Text field JSON element which has boolean example 

```
{
		"name": "Entity-address",
		"type": "text-area",
		"label": "Your Entity's Street Address",
		"placeholder": "123 Main Street, Apt. 45",
		"value": "123 Main Street, Apt. 45",
		"boolean": false
	},
```
9. text-area type 
10. array type 
```
{
		"name": "Board-member",
		"type": "text",
		"label": "Board member",
		"placeholder": "Mr. John Doe",
		"value": "Mr. John Doe",
		"count": 1
	},
```
9. use browser-storage for default form which includes name, address, entity, (will provide form) to pre-populate forms

**Comment by webel** [comment]
8 - The boolean example, is that to by default not fill in the address?
9 -  there's "textarea" - I'll look at the UI of textareas thou as it might just look like input with a draggable corner.

**Comment by tankbottoms** [comment]
The idea with this is that we could have some text which if the check box is enabled would be enabled in the text body, otherwise left out. It would be handy to insert clauses which could be optional.

**Comment by tankbottoms** [comment]
Also, if you could bring over the image component from the activity feed in juicebox.wtf so that when we include an image which will likely be sized to fit the layout by default they are clickable into a detail preview mode. I added calculator screenshots for DAOLABs. Also when clicking around in the menu and then clicking the heading between legal and daolabs the menus seem to be updated but not fully refreshed and getting into some funky state.

**Comment by tankbottoms** [comment]
Natasha is laying out the following. Document left side menu to collapse into a document nib, like the collapsed menu you created for https://meows-svg.on.fleek.co/, and on top of this or in another nib, a form icon, which expands and contracts variables are exposed with the update button effecting the main page - which is the legal document and the chapter headings only. At the top of the page are icons for docx, pdf to allow for downloading of the then generated document. 
[documents.zip](https://github.com/tankbottoms/daolabs-docs/files/9569898/documents.zip) + markdown

Natasha will experiment later with having a user login, theme dark and light mode, where the user default page has information form which would pre-populate the various forms and save the users information in browser storage. Then addition to downloading the document locally an add document to template/signing workflow where the document can be sent to an email address or assigned to login address where users can digital sign the document. This will be just designed and thought about but not remotely needed for this version, only to export the file as a standalone application and add to a project for a legal application.

**Comment by tankbottoms** [comment]
Updated the DAOLABS logo because this is very important, but failed at doing anything about the top padding.

**Comment by tankbottoms** [comment]
Screenshots of proposed layout updates for moving the menu into a hide-able tab, as well as the form so that the legal doc can enjoy the main width with its chapters in full glory. the nib or half circle tabs could be larger and the form expanded need not push the content down but instead overlay for those with enough horizontal flex. If this satisfies the sensibility of @webel  then perhaps we can have @codecookerpro make proposed edits in a branch and do the pull request for integration of docx, pdf, markdown etc. downloads. 

![menu](https://user-images.githubusercontent.com/97219477/190425589-9dc53f68-e42e-479b-88a7-bc3d68dc346f.png)


![menu-collapsed-form-viewable-to-expand](https://user-images.githubusercontent.com/97219477/190425666-8c5d7a73-bb5e-4cb1-a1d4-e840d083b1d5.png)

![menu-and-form-collapsed-into-tab-mode](https://user-images.githubusercontent.com/97219477/190425668-2f786b71-b35a-4629-85e8-e773f35e24ec.png)

![menu-collapsed-into-tab-mode-content-need-not-pushed-down](https://user-images.githubusercontent.com/97219477/190425671-469a79af-f65c-411a-bd7d-d5a88a6b100a.png)

![menu-collapse-tool](https://user-images.githubusercontent.com/97219477/190425675-0d472f8c-0456-4db9-b669-9d621f282d5b.png)

**Comment by tankbottoms** [comment]
Main page content need not be pushed down, rather the form left drawer may be z-indexed over. the share button need not be implemented so it can be disabled, with the signing document, the markdown, docx, pdfs allow for the content to be exported, download.

**Comment by tankbottoms** [comment]
After this generation phase, its reasonable to consider bringing it over to https://github.com/tankbottoms/juicebox-legal-vending for Juicebox styling. but these edits intend to be the last stylistic change before doing the arduous legal content pass.

**Comment by tankbottoms** [comment]
Updated the layering of the form, see DAOLABS, https://www.figma.com/file/8orucP9iXPsWnPhJa1guUF/JB-Treasury-UX?node-id=3817%3A96003 - focus on the bottom options with out heavy shadow

![Screen Shot 2022-09-15 at 7 02 29 PM](https://user-images.githubusercontent.com/97219477/190523383-1253be95-d453-43ab-b27c-211eae1e587f.png)

The following is the preferred layout of the main menu collapsed under the form tab which shows the edge of the forms so that the user knows this is the form layer. 

![Frame 1180](https://user-images.githubusercontent.com/97219477/190523411-df108263-810b-43d4-807b-e5ba0f5c2db7.png)

![Frame 1181](https://user-images.githubusercontent.com/97219477/190523538-6d93c258-dab3-4016-ad4b-97533dc9df29.png)

**Comment by webel** [comment]
Ohhh looks mighty fine, I'll get to this after slugging away elsewhere for a few hours first.

**Comment by tankbottoms** [comment]
@webel @spaceshift made a bunch of updates with 1) fixing the footer next and previous links, 2) creating the collapsable menu, 3) creating the collapsable form. please review them and as fold into main as you approve. on my screen at least, the site looks nice at 90% zoom in chrome, so updating the layout and font to this, your call. form update doesn't update the bookmarks, and the main contract content could be centered better, i'm not a fan of this. 

![Screen Shot 2022-09-20 at 6 57 50 AM](https://user-images.githubusercontent.com/97219477/191241663-6b5568f2-5510-4961-9948-94becce80995.png)

Rather it could be 50px more to the right, and the left section could be blank if the form was not expanded, or with form. But that the menu or form would be expanding over the blank space, which i think is fine. Once you update main, I think we should close this thread out and start new issues with the remaining export features.

![Screen Shot 2022-09-20 at 7 03 43 AM](https://user-images.githubusercontent.com/97219477/191241870-9456f12a-76c1-4505-87fb-f40ae4b52fa5.png)

**Comment by webel** [comment]
Close after merge to main, see https://github.com/DAOLABS-WTF/daolabs-legal-documents/issues/15 for more issues.
